name = "snowy-mud-6e88"
compatibility_date = "2026-07-03"
main = "src/worker.js"

[[routes]]
pattern = "mazen.zb-store.com"
custom_domain = true

[assets]
directory = "."
binding = "ASSETS"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "school_knowledge_index"

[[ratelimits]]
name = "CHAT_RATE_LIMITER"
namespace_id = "151001"

  [ratelimits.simple]
  limit = 20
  period = 60

[[ratelimits]]
name = "ADMIN_AUTH_RATE_LIMITER"
namespace_id = "151002"

  [ratelimits.simple]
  limit = 5
  period = 60

[secrets]
required = [ "RATE_LIMIT_SALT" ]

[[d1_databases]]
binding = "UNANSWERED_DB"
database_name = "school-unanswered-questions"
database_id = "34747b5a-9df1-4a7d-98b0-5cbce29358ae"


[[d1_databases]]
binding = "PLATFORM_DB"
database_name = "school-platform-db"
database_id = "8b9e3fb9-ff59-4834-82e9-01c45409d484"
migrations_dir = "migrations/platform"
